### ISSUE TITLE
Autenticação usando token

### ISSUE THREAD

**Issue by brunoscota** [dev-senior-com-br/senior-core-node#50]
os tokens gerados no sistema durante a autenticação tem um prazo para expirar? é possivel autenticar com um token sem data de expiração ? 

Obrigado

**Comment by roquecp** [comment]
Olá @brunoscota.

Sim, os tokens possuem um prazo de expiração que, normalmente, é de 7 dias. Este prazo está contido no retorno da ação de login, atributo "jsonToken". Mas **não é possível** criar um token sem prazo de expiração.

Um exemplo de como obter as informações do atributo "jsonToken" está neste fonte [authentication-example.js](https://github.com/dev-senior-com-br/senior-core-node/blob/master/examples/authentication-example.js).

Há como renovar um token utilizando o "refreshToken", mas seu código precisará saber lidar com uma eventual expiração de token e efetuar um `refreshToken` - lembrando que mesmo o refreshToken possui expiração que normalmente é o dobro do tempo do token.

Outra opção é efetuar um novo `login`.

Um informação importante é que, caso o tenant no qual você está autenticando estiver configurado para `Reutilizar o mesmo token para as múltiplas sessões do usuário` e este usuário em algum momento fizer um logoff (mesmo que em outro dispositivo), o token será invalidado e será necessário efetuar um novo `login`.
Esta informação pode ser consultada através do usuário admin do tenant em Tecnologia / Administração / Gestão dos Tenants / Configurar (guia autenticação)

Informações adicionais sobre a API podem ser encontradas nos tutoriais do dev.senior, como esta da autenticação: https://dev.senior.com.br/documentacao/tutorial-da-api-authentication/login/

Em caso de novas dúvidas sobre este ou outros comportamentos da plataforma senior X, utilize o nosso no [fórum](https://dev.senior.com.br/forums/) no dev.senior.

Att,
Roque

**Comment by brunoscota** [comment]
Ah! muito obrigado!
